import { Button, Empty, Form, Input, List, Popconfirm, Select, Space, Spin, Switch, Tabs, Typography } from 'antd';
import { CloseOutlined, DeleteOutlined, FolderOpenOutlined, InboxOutlined } from '@ant-design/icons';

const { Text } = Typography;
const options = (items = []) => items.map((item) => ({ value: item.id, label: item.name }));
const preview = (text, limit = 240) => text.length > limit ? `${text.slice(0, limit).trimEnd()}?` : text;
export function PreviewBlock({ label, text, accent }) { return <div className={accent ? 'preview-block accent' : 'preview-block'}><label>{label}</label><pre>{preview(text, 260)}</pre></div>; }
export function ActionBar({ children }) { return <footer className="action-bar">{children}</footer>; }

export function ControlPanel({ payload, busy, notice, onClose, onChange, onChooseDirectory, onImport, onDelete, onSave, onTest }) {
  const data = payload.settings;
  const catalog = (label, items, importCommand, deleteCommand) => <><div className="catalog-heading"><Text>{label}</Text><Button size="small" icon={<InboxOutlined />} onClick={() => onImport(importCommand, `导入${label}`, label)}>导入</Button></div><List size="small" dataSource={items} locale={{ emptyText: <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description={`暂无${label}`} /> }} renderItem={(item) => <List.Item actions={[<Popconfirm key="delete" title={`删除「${item.name}」？`} description="将删除已导入的本地目录，无法撤销。" okText="删除" cancelText="取消" onConfirm={() => onDelete(deleteCommand, item.id, label)}><Button danger type="text" size="small" icon={<DeleteOutlined />} /></Popconfirm>]}><List.Item.Meta title={item.name} description={item.path} /></List.Item>} /></>;
  return <main className="control-panel"><header className="palette-titlebar"><div className="palette-drag-region" data-tauri-drag-region><span className="app-mark">CONTROL PANEL</span></div><div data-no-window-drag><Button type="text" size="small" icon={<CloseOutlined />} onClick={onClose}>关闭</Button></div></header><div className="control-notice">{busy && <Spin size="small" />}{notice || '本地配置与资料管理'}</div>
    <Tabs size="small" items={[
      { key: 'model', label: '模型与权限', children: <Form layout="vertical" className="compact-form"><Form.Item label="DeepSeek 模型"><Input size="small" value={data.model} onChange={(event) => onChange('model', event.target.value)} /></Form.Item><Form.Item label="DeepSeek API Key"><Input.Password size="small" value={data.apiKey || ''} placeholder={payload.apiKeyConfigured ? '已配置；留空保留当前 Key' : '尚未配置'} onChange={(event) => onChange('apiKey', event.target.value)} /></Form.Item><Form.Item label="允许 Agent 联网"><Switch size="small" checked={data.allowNetwork} onChange={(value) => onChange('allowNetwork', value)} checkedChildren="允许" unCheckedChildren="关闭" /></Form.Item><Form.Item label="Reference Context"><Space.Compact block><Select size="small" value={data.referenceShortcut || 'Ctrl+Shift+T'} options={[{ value: 'Ctrl+Shift+T', label: 'Ctrl+Shift+T' }, { value: 'Ctrl+Alt+T', label: 'Ctrl+Alt+T' }]} onChange={(value) => onChange('referenceShortcut', value)} /><Select size="small" value={data.referenceCaptureMode || 'selection'} options={[{ value: 'selection', label: 'Selection with toast' }, { value: 'clipboard', label: 'Clipboard without toast' }]} onChange={(value) => onChange('referenceCaptureMode', value)} /></Space.Compact></Form.Item><ActionBar><Button onClick={onTest} loading={busy}>测试 API</Button><Button type="primary" onClick={onSave} loading={busy}>保存</Button></ActionBar></Form> },
      { key: 'directories', label: '资料目录', children: <Form layout="vertical" className="compact-form"><Form.Item label="Agent 根目录"><Space.Compact block><Input size="small" value={data.agentsRoot} onChange={(event) => onChange('agentsRoot', event.target.value)} /><Button size="small" icon={<FolderOpenOutlined />} onClick={() => onChooseDirectory('agentsRoot', '选择 Agent 根目录')} /></Space.Compact></Form.Item><Form.Item label="知识库根目录"><Space.Compact block><Input size="small" value={data.knowledgeBasesRoot} onChange={(event) => onChange('knowledgeBasesRoot', event.target.value)} /><Button size="small" icon={<FolderOpenOutlined />} onClick={() => onChooseDirectory('knowledgeBasesRoot', '选择知识库根目录')} /></Space.Compact></Form.Item><Form.Item label="默认 Agent"><Select size="small" value={data.defaultAgent} options={[{ value: '', label: '未选择' }, ...options(payload.agents)]} onChange={(value) => onChange('defaultAgent', value)} /></Form.Item><Form.Item label="默认知识库"><Select size="small" value={data.defaultKnowledgeBase} options={[{ value: '', label: '未选择' }, ...options(payload.knowledgeBases)]} onChange={(value) => onChange('defaultKnowledgeBase', value)} /></Form.Item><ActionBar><Button type="primary" onClick={onSave} loading={busy}>保存</Button></ActionBar></Form> },
      { key: 'agents', label: 'Agent', children: catalog('Agent', payload.agents, 'import_agent', 'delete_agent') },
      { key: 'knowledge', label: '知识库', children: catalog('知识库', payload.knowledgeBases, 'import_knowledge_base', 'delete_knowledge_base') },
    ]} />
  </main>;
}
